#%RAML 1.0 NamedExample
{
    "suppressedErrors": [],
    "errorType": {
        "identifier": "NOT_FOUND",
        "parentErrorType": {
            "identifier": "ANY",
            "parentErrorType": {
                "identifier": "ANY",
                "parentErrorType": null,
                "namespace": "MULE"
            },
            "namespace": "APIKIT"
        },
        "namespace": "APIKIT"
    },
    "childErrors": [],
    "errorMessage": null,
    "cause": {
        "verboseMessage": "\r\n********************************************************************************\r\nMessage               : /validaleituraf\r\nElement               : exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31\r\nElement DSL           : <apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>\r\nError type            : APIKIT:NOT_FOUND\r\nFlowStack             : at exp-portalweb-dev-main(exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31)\r\n--------------------------------------------------------------------------------\r\nRoot Exception stack trace:\r\norg.mule.module.apikit.exception.NotFoundException: /validaleituraf\r\n\r\n********************************************************************************\r\n",
        "localizedMessage": "/validaleituraf",
        "summaryMessage": "\r\n********************************************************************************\r\nMessage               : /validaleituraf\r\nElement               : exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31\r\nElement DSL           : <apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>\r\nError type            : APIKIT:NOT_FOUND\r\nFlowStack             : at exp-portalweb-dev-main(exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31)\r\n\r\n  (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)\r\n********************************************************************************\r\n",
        "cause": null,
        "message": "/validaleituraf",
        "i18nMessage": {
            "code": -1,
            "nextMessage": null,
            "message": "/validaleituraf",
            "args": []
        },
        "detailedMessage": "\r\n********************************************************************************\r\nMessage               : /validaleituraf\r\nElement               : exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31\r\nElement DSL           : <apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>\r\nError type            : APIKIT:NOT_FOUND\r\nFlowStack             : at exp-portalweb-dev-main(exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31)\r\n\r\n  (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)\r\n********************************************************************************\r\n",
        "stringRepresentation": "APIKIT:NOT_FOUND",
        "additionalInfo": {},
        "messageCode": -1,
        "stackTrace": [],
        "suppressed": [],
        "exceptionInfo": {
            "dslSource": "<apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>",
            "alreadyLogged": true,
            "errorType": {
                "identifier": "NOT_FOUND",
                "parentErrorType": {
                    "identifier": "ANY",
                    "parentErrorType": {
                        "identifier": "ANY",
                        "parentErrorType": null,
                        "namespace": "MULE"
                    },
                    "namespace": "APIKIT"
                },
                "namespace": "APIKIT"
            },
            "flowStack": {
                "elements": [
                    {
                        "creationTime": 1690863375041,
                        "flowName": "exp-portalweb-dev-main",
                        "elapsedTimeLong": 26230,
                        "creationTimeLong": 1690863375041,
                        "processorPath": "exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31",
                        "chainIdentifier": {
                            "name": "flow",
                            "namespace": "mule",
                            "namespaceUri": "http://www.mulesoft.org/schema/mule/core"
                        },
                        "elapsedTime": 26230
                    }
                ]
            },
            "location": "exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31",
            "suppressedCauses": []
        },
        "info": {
            "Error type": {
                "identifier": "NOT_FOUND",
                "parentErrorType": {
                    "identifier": "ANY",
                    "parentErrorType": {
                        "identifier": "ANY",
                        "parentErrorType": null,
                        "namespace": "MULE"
                    },
                    "namespace": "APIKIT"
                },
                "namespace": "APIKIT"
            },
            "Element": "exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31",
            "Element DSL": "<apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>",
            "FlowStack": {
                "elements": [
                    {
                        "creationTime": 1690863375041,
                        "flowName": "exp-portalweb-dev-main",
                        "elapsedTimeLong": 26230,
                        "creationTimeLong": 1690863375041,
                        "processorPath": "exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31",
                        "chainIdentifier": {
                            "name": "flow",
                            "namespace": "mule",
                            "namespaceUri": "http://www.mulesoft.org/schema/mule/core"
                        },
                        "elapsedTime": 26230
                    }
                ]
            }
        }
    },
    "description": "/validaleituraf",
    "detailedDescription": "/validaleituraf",
    "failingComponent": "exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31"
}