#%RAML 1.0 NamedExample
{
  "code": 401,
  "reason": "Unauthorized",
  "timeStamp": "2023-08-01T09:00:27.4969626-03:00",
  "message": "Required credentials are missing or invalid.",
  "errorDescription": "Error description Mulesoft.",
  "correlationId": "fe74a690-3062-11ee-ad3f-00d76d3bb9e8"
}