#%RAML 1.0 NamedExample
{
  "code": 408,
  "reason": "Request Timeout",
  "timeStamp": "2023-08-01T09:00:27.4969626-03:00",
  "message": "The requested resource status code indicates that the server did not receive a complete request message within the time that it was prepared to wait.",
  "errorDescription": "Error description Mulesoft.",
  "correlationId": "fe74a690-3062-11ee-ad3f-00d76d3bb9e8"
}