#%RAML 1.0 NamedExample
{
  "code": 503,
  "reason": "Service Unavailable",
  "timeStamp": "2023-08-01T09:00:27.4969626-03:00",
  "message": "The 503 (Service Unavailable) status code indicates that the server is currently unable to handle the request due to a temporary overload or scheduled maintenance, which will likely be alleviated after some delay.",
  "errorDescription": "/validaleituraf",
  "correlationId": "fe74a690-3062-11ee-ad3f-00d76d3bb9e8",
  "flowName": "exp-portalweb-dev-main",
  "routerApkit": "<apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>",
  "failingComponent": "exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31",
  "detailedMessage": "\r\n********************************************************************************\r\nMessage               : /validaleituraf\r\nElement               : exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31\r\nElement DSL           : <apikit:router config-ref=\"exp-portalweb-dev-config\"></apikit:router>\r\nError type            : APIKIT:NOT_FOUND\r\nFlowStack             : at exp-portalweb-dev-main(exp-portalweb-dev-main/processors/1 @ exp-portalweb-dev-07-28-2023-brunolim:exp-portalweb-dev.xml:31)\r\n\r\n  (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)\r\n********************************************************************************\r\n"
}