#%RAML 1.0 NamedExample
{
  "code": 429,
  "reason": "Too Many Requests",
  "timeStamp": "2023-08-01T09:00:27.4969626-03:00",
  "message": "The server is refusing to handle the request because a rate limit has been exceeded.",
  "errorDescription": "Error description Mulesoft.",
  "correlationId": "fe74a690-3062-11ee-ad3f-00d76d3bb9e8"
}